# Flag the junk property listings

### Data Loading and pre processing

In [2]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np

In [3]:
datafile_train=r'C:\Users\isaac\Documents\Python Scripts\Project\Project 5 Real Estate\Property_train.csv'
datafile_test=r'C:\Users\isaac\Documents\Python Scripts\Project\Project 5 Real Estate\Property_test_share.csv'
bd_train=pd.read_csv(datafile_train)
bd_test=pd.read_csv(datafile_test)

In [4]:
bd_train.head()

,Junk,InteriorsStyle,PriceIndex8,ListDate,Material,PriceIndex9,Agency,AreaIncomeType,EnvRating,PriceIndex7,...,Region,PriceIndex5,SubModel,Facade,State,NormalisedPopulation,BuildYear,RegionType,PropertyAge,PriceIndex2
0,0,6LLJ,14674.0,9/7/2010,UT7W,8270,CAT3,B,missing,13143.0,...,A,9022.0,6E9G,GREEN,MD,42077,2008,A,2,10692.0
1,1,XZ9F,4172.0,1/7/2009,PRN0,3890,CAT2,B,missing,3461.0,...,A,2742.0,FIVQ,SILVER,OK,77258,2002,A,7,3615.0
2,0,QWEV,8210.0,6/23/2010,A9RA,5900,CAT1,B,missing,6922.0,...,A,3768.0,4K0H,SILVER,SC,94514,2004,A,6,5805.0
3,0,MK2K,7309.0,3/19/2009,RRJQ,7460,OTHER,A,missing,6300.0,...,A,5370.0,ZLXY,WHITE,NC,82302,2002,C,7,6444.0
4,0,GK4G,9182.0,3/3/2010,HE5A,6400,OTHER,B,missing,8330.0,...,A,4803.0,FIVQ,SILVER,SC,49176,2007,B,3,6286.0

In [5]:
bd_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62035 entries, 0 to 62034
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Junk                   62035 non-null  int64
 1   InteriorsStyle         62035 non-null  object
 2   PriceIndex8            62035 non-null  object
 3   ListDate               62035 non-null  object
 4   Material               62035 non-null  object
 5   PriceIndex9            62035 non-null  int64
 6   Agency                 62035 non-null  object
 7   AreaIncomeType         62035 non-null  object
 8   EnvRating              62035 non-null  object
 9   PriceIndex7            62035 non-null  object
 10  ExpeditedListing       62035 non-null  int64
 11  PriceIndex4            62035 non-null  object
 12  PriceIndex1            62035 non-null  object
 13  PriceIndex6            62035 non-null  object
 14  PRIMEUNIT              62035 non-null  object
 15  Channel                62035 non-null  object
 16  Zip                    62035 non-null  int64
 17  InsurancePremiumIndex  62035 non-null  int64
 18  PlotType               62035 non-null  object
 19  Architecture           62035 non-null  object
 20  PriceIndex3            62035 non-null  object
 21  Region                 62035 non-null  object
 22  PriceIndex5            62035 non-null  object
 23  SubModel               62035 non-null  object
 24  Facade                 62035 non-null  object
 25  State                  62035 non-null  object
 26  NormalisedPopulation   62035 non-null  int64
 27  BuildYear              62035 non-null  int64
 28  RegionType             62035 non-null  object
 29  PropertyAge            62035 non-null  int64
 30  PriceIndex2            62035 non-null  object
dtypes: int64(8), object(23)
memory usage: 14.7+ MB

In [6]:
bd_train.dtypes

Junk                      int64
InteriorsStyle           object
PriceIndex8              object
ListDate                 object
Material                 object
PriceIndex9               int64
Agency                   object
AreaIncomeType           object
EnvRating                object
PriceIndex7              object
ExpeditedListing          int64
PriceIndex4              object
PriceIndex1              object
PriceIndex6              object
PRIMEUNIT                object
Channel                  object
Zip                       int64
InsurancePremiumIndex     int64
PlotType                 object
Architecture             object
PriceIndex3              object
Region                   object
PriceIndex5              object
SubModel                 object
Facade                   object
State                    object
NormalisedPopulation      int64
BuildYear                 int64
RegionType               object
PropertyAge               int64
PriceIndex2              object
dtype: object

In [7]:
bd_train.shape

(62035, 31)

In [8]:
bd_test.shape

(10948, 30)

In [9]:
bd_train.isnull().sum()

Junk                     0
InteriorsStyle           0
PriceIndex8              0
ListDate                 0
Material                 0
PriceIndex9              0
Agency                   0
AreaIncomeType           0
EnvRating                0
PriceIndex7              0
ExpeditedListing         0
PriceIndex4              0
PriceIndex1              0
PriceIndex6              0
PRIMEUNIT                0
Channel                  0
Zip                      0
InsurancePremiumIndex    0
PlotType                 0
Architecture             0
PriceIndex3              0
Region                   0
PriceIndex5              0
SubModel                 0
Facade                   0
State                    0
NormalisedPopulation     0
BuildYear                0
RegionType               0
PropertyAge              0
PriceIndex2              0
dtype: int64

In [10]:
bd_train['data']='train'
bd_test['data']='test'

all_data=pd.concat([bd_train,bd_test],axis = 0,sort=False)

In [11]:
all_data.shape

(72983, 32)

In [8]:
all_data.sample(5)

,Junk,InteriorsStyle,PriceIndex8,ListDate,Material,PriceIndex9,Agency,AreaIncomeType,EnvRating,PriceIndex7,...,PriceIndex5,SubModel,Facade,State,NormalisedPopulation,BuildYear,RegionType,PropertyAge,PriceIndex2,data
35696,0.0,FSJW,10938.0,2010-01-20,3F8B,7735,CAT1,A,missing,9911.0,...,6226.0,K8LM,GREEN,TX,87472,2004,A,6,7110.0,train
38076,0.0,HZZU,4539.0,2009-04-08,ZCI3,5000,CAT2,B,missing,3332.0,...,2622.0,JQH4,BLUE,CA,34863,2002,A,7,3740.0,train
51182,0.0,6UCD,12024.0,2010-10-13,ZCI3,7925,CAT2,B,missing,11134.0,...,7433.0,FIVQ,SILVER,VA,42051,2008,A,2,8693.0,train
1486,0.0,YOC7,10781.0,2010-12-16,RRJQ,5450,OTHER,B,GREEN,9498.0,...,6407.0,E75G,GOLD,NC,59689,2007,B,3,6470.0,train
37875,0.0,CKUI,14144.0,2010-10-20,NYFD,9335,CAT2,A,missing,12117.0,...,8406.0,3ZS5,WHITE,TN,79186,2006,A,4,9988.0,train

In [9]:
bd_train['ListDate'].dtypes

dtype('O')

In [12]:
from sklearn.pipeline import Pipeline,FeatureUnion
from sklearn.base import BaseEstimator, TransformerMixin

from mypipes_exercise import *

### Using Pipelines for processing data

In [13]:
p1=pdPipeline([
    ('var_select',VarSelector(['PriceIndex9','PriceIndex8', 'PriceIndex7', 'PriceIndex4', 'PriceIndex1', 'PriceIndex6',
                               'InsurancePremiumIndex','PriceIndex3', 'PriceIndex5', 'NormalisedPopulation', 'PriceIndex2'])),
    ('object_to_numeric',convert_to_numeric()),
    ('missing_trt',DataFrameImputer())
])
p2=pdPipeline([
    ('var_select',VarSelector(['InteriorsStyle', 'Material', 'Agency', 'AreaIncomeType',
                               'EnvRating','ExpeditedListing','PRIMEUNIT', 'Channel', 'PlotType', 'Architecture',
                               'Region', 'SubModel', 'Facade', 'State', 'BuildYear', 'RegionType','Zip', 'PropertyAge'])),
    ('missing_trt',DataFrameImputer()),
    ('create_dummies',get_dummies_Pipe(500))
])
p3=pdPipeline([
    ('var_select',VarSelector(['ListDate'])),
    ('covert_to_datetime',convert_to_datetime()),
    ('cyclic_dates',cyclic_features())
])
p4=pdPipeline([
    ('var_select',VarSelector(['data']))
])

In [14]:
data_pipe=FeatureUnion([
    ('obj_num',p1),
    ('obj_to_dum',p2),
    ('cyclic',p3),
    ('data',p4)
])

In [15]:
all_data_pipe=pd.DataFrame(data=data_pipe.fit_transform(all_data),
                     columns=data_pipe.get_feature_names())

In [16]:
all_data_pipe.shape

(72983, 239)

In [17]:
all_data_pipe.sample(5)

,obj_num__PriceIndex9,obj_num__PriceIndex8,obj_num__PriceIndex7,obj_num__PriceIndex4,obj_num__PriceIndex1,obj_num__PriceIndex6,obj_num__InsurancePremiumIndex,obj_num__PriceIndex3,obj_num__PriceIndex5,obj_num__NormalisedPopulation,...,obj_to_dum__PropertyAge_1,obj_to_dum__PropertyAge_8,obj_to_dum__PropertyAge_9,cyclic__ListDate_week_sin,cyclic__ListDate_week_cos,cyclic__ListDate_month_sin,cyclic__ListDate_month_cos,cyclic__ListDate_month_day_sin,cyclic__ListDate_month_day_cos,data__data
31101,8600.0,18766.0,16940.0,18594.0,14631.0,16913.0,1918.0,16301.0,15222.0,92271.0,...,0,0,0,0.781831,0.62349,-0.5,-0.866025,-0.897805,-0.440394,train
62423,6215.0,8756.0,7060.0,8853.0,4529.0,5445.0,1974.0,7394.0,4203.0,76753.0,...,0,0,0,0.433884,-0.900969,0.866025,0.5,-0.485302,-0.874347,test
39725,4630.0,7529.0,6361.0,7529.0,5427.0,6508.0,1389.0,6361.0,5427.0,75243.0,...,0,0,0,0.974928,-0.222521,-0.5,-0.866025,0.101168,-0.994869,train
55082,7065.0,11029.0,9763.0,11607.0,6055.0,7397.0,1053.0,9917.0,6156.0,98326.0,...,0,0,0,0.433884,-0.900969,-0.866025,-0.5,0.848644,0.528964,train
26045,4900.0,8691.0,7206.0,6757.0,2844.0,5554.0,2506.0,5996.0,3883.0,98195.0,...,0,0,0,0.974928,-0.222521,-0.0,1.0,0.201299,0.97953,train

In [18]:
all_data_pipe.shape

(72983, 239)

In [19]:
all_data_pipe.sample(5)

,obj_num__PriceIndex9,obj_num__PriceIndex8,obj_num__PriceIndex7,obj_num__PriceIndex4,obj_num__PriceIndex1,obj_num__PriceIndex6,obj_num__InsurancePremiumIndex,obj_num__PriceIndex3,obj_num__PriceIndex5,obj_num__NormalisedPopulation,...,obj_to_dum__PropertyAge_1,obj_to_dum__PropertyAge_8,obj_to_dum__PropertyAge_9,cyclic__ListDate_week_sin,cyclic__ListDate_week_cos,cyclic__ListDate_month_sin,cyclic__ListDate_month_cos,cyclic__ListDate_month_day_sin,cyclic__ListDate_month_day_cos,data__data
482,7515.0,10193.0,8806.0,10664.0,5554.0,6098.0,803.0,9196.0,5059.0,77384.0,...,0,0,0,-0.433884,-0.900969,-0.866025,0.5,0.998717,-0.050649,train
35155,6900.0,11739.0,11237.0,9134.0,7407.0,7500.0,754.0,8500.0,6966.0,51157.0,...,1,0,0,0.0,1.0,-0.866025,0.5,0.651372,-0.758758,train
32086,8260.0,9825.0,8235.0,9634.0,7134.0,8634.0,1974.0,8205.0,7162.0,76530.0,...,0,0,0,0.974928,-0.222521,1.0,0.0,0.724793,0.688967,train
10656,5150.0,8710.0,7185.0,9149.0,3856.0,4660.0,569.0,7559.0,3844.0,72631.0,...,0,0,0,0.974928,-0.222521,-0.866025,-0.5,0.724793,0.688967,train
19830,5680.0,8464.0,7514.0,9225.0,4488.0,5206.0,920.0,7842.0,3928.0,71836.0,...,0,0,0,0.781831,0.62349,0.0,-1.0,0.998717,-0.050649,train

In [21]:
x_train = all_data_pipe[all_data_pipe['data__data'] == "train"]

In [22]:
x_train.drop(['data__data'],1,inplace=True)

In [23]:
x_test = all_data_pipe[all_data_pipe['data__data'] == "test"]

In [24]:
x_test.drop(['data__data'],1,inplace=True)

In [25]:
x_train

,obj_num__PriceIndex9,obj_num__PriceIndex8,obj_num__PriceIndex7,obj_num__PriceIndex4,obj_num__PriceIndex1,obj_num__PriceIndex6,obj_num__InsurancePremiumIndex,obj_num__PriceIndex3,obj_num__PriceIndex5,obj_num__NormalisedPopulation,...,obj_to_dum__PropertyAge_7,obj_to_dum__PropertyAge_1,obj_to_dum__PropertyAge_8,obj_to_dum__PropertyAge_9,cyclic__ListDate_week_sin,cyclic__ListDate_week_cos,cyclic__ListDate_month_sin,cyclic__ListDate_month_cos,cyclic__ListDate_month_day_sin,cyclic__ListDate_month_day_cos
0,8270.0,14674.0,13143.0,14224.0,9217.0,10387.0,623.0,13108.0,9022.0,42077.0,...,0,0,0,0,0.781831,0.62349,-1.0,-0.0,0.988468,0.151428
1,3890.0,4172.0,3461.0,4404.0,2958.0,3400.0,1689.0,3695.0,2742.0,77258.0,...,1,0,0,0,0.974928,-0.222521,0.5,0.866025,0.988468,0.151428
2,5900.0,8210.0,6922.0,8952.0,4568.0,4862.0,2351.0,7730.0,3768.0,94514.0,...,0,0,0,0,0.974928,-0.222521,0.0,-1.0,-0.998717,-0.050649
3,7460.0,7309.0,6300.0,7460.0,5361.0,6305.0,1933.0,6290.0,5370.0,82302.0,...,1,0,0,0,0.433884,-0.900969,1.0,0.0,-0.651372,-0.758758
4,6400.0,9182.0,8330.0,9846.0,5428.0,5718.0,482.0,8583.0,4803.0,49176.0,...,0,0,0,0,0.974928,-0.222521,1.0,0.0,0.571268,0.820763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62030,8745.0,15110.0,13468.0,15279.0,9584.0,11626.0,1893.0,13858.0,10012.0,87562.0,...,0,0,0,0,0.974928,-0.222521,1.0,0.0,-0.0,1.0
62031,5360.0,9456.0,8543.0,9420.0,5187.0,6683.0,594.0,8600.0,5439.0,80201.0,...,0,0,0,0,0.974928,-0.222521,-0.866025,0.5,-0.790776,-0.612106
62032,6670.0,8730.0,7217.0,8730.0,6219.0,7620.0,1313.0,7217.0,6219.0,65983.0,...,0,0,0,0,0.781831,0.62349,0.5,-0.866025,-0.651372,-0.758758
62033,6600.0,8546.0,7316.0,8546.0,6311.0,7450.0,837.0,7316.0,6311.0,59780.0,...,0,0,0,0,0.433884,-0.900969,0.866025,-0.5,-0.201299,0.97953
62034,8700.0,12658.0,12002.0,13558.0,8698.0,9514.0,762.0,12824.0,8930.0,38703.0,...,0,1,0,0,0.974928,-0.222521,-0.5,0.866025,0.571268,0.820763

In [26]:
x_test

,obj_num__PriceIndex9,obj_num__PriceIndex8,obj_num__PriceIndex7,obj_num__PriceIndex4,obj_num__PriceIndex1,obj_num__PriceIndex6,obj_num__InsurancePremiumIndex,obj_num__PriceIndex3,obj_num__PriceIndex5,obj_num__NormalisedPopulation,...,obj_to_dum__PropertyAge_7,obj_to_dum__PropertyAge_1,obj_to_dum__PropertyAge_8,obj_to_dum__PropertyAge_9,cyclic__ListDate_week_sin,cyclic__ListDate_week_cos,cyclic__ListDate_month_sin,cyclic__ListDate_month_cos,cyclic__ListDate_month_day_sin,cyclic__ListDate_month_day_cos
62035,6015.0,10645.0,9568.0,12432.0,6986.0,7133.0,728.0,10860.0,5911.0,67549.0,...,0,0,0,0,0.974928,-0.222521,-1.0,-0.0,-0.968077,-0.250653
62036,7625.0,9891.0,8888.0,12173.0,5954.0,6544.0,1334.0,10166.0,5370.0,56570.0,...,0,0,0,0,-0.433884,-0.900969,1.0,0.0,0.651372,-0.758758
62037,6900.0,8426.0,7911.0,9134.0,7407.0,7339.0,754.0,8500.0,6862.0,51840.0,...,0,1,0,0,0.0,1.0,-0.866025,0.5,0.651372,-0.758758
62038,6475.0,9269.0,7773.0,8500.0,4241.0,6143.0,1373.0,7294.0,4872.0,83300.0,...,0,0,0,0,0.433884,-0.900969,0.5,-0.866025,-0.790776,-0.612106
62039,3960.0,5366.0,4134.0,5211.0,3352.0,4506.0,2939.0,4120.0,3365.0,95035.0,...,0,0,0,0,0.781831,0.62349,0.5,0.866025,0.485302,-0.874347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72978,7500.0,13956.0,12860.0,10415.0,8497.0,9703.0,920.0,9677.0,8879.0,51629.0,...,0,1,0,0,0.0,1.0,-0.866025,0.5,-0.848644,0.528964
72979,5425.0,7880.0,6845.0,8521.0,3739.0,4716.0,533.0,6860.0,3594.0,69990.0,...,0,0,0,0,0.781831,0.62349,-1.0,-0.0,-0.571268,0.820763
72980,7700.0,16417.0,14663.0,13555.0,10199.0,11939.0,803.0,11515.0,10424.0,73737.0,...,0,0,0,0,0.974928,-0.222521,-0.5,0.866025,-0.485302,-0.874347
72981,6300.0,11311.0,10292.0,11733.0,6735.0,8075.0,983.0,10475.0,6755.0,85960.0,...,0,0,0,0,0.0,1.0,-0.0,1.0,0.937752,0.347305
72982,5000.0,4657.0,3524.0,4223.0,2547.0,3849.0,1020.0,3251.0,2800.0,69307.0,...,0,0,0,0,0.974928,-0.222521,-0.866025,-0.5,0.651372,-0.758758

In [22]:
x_train.drop(['data__data'],1,inplace=True)

In [23]:
x_train

,obj_num__PriceIndex9,obj_num__PriceIndex8,obj_num__PriceIndex7,obj_num__PriceIndex4,obj_num__PriceIndex1,obj_num__PriceIndex6,obj_num__InsurancePremiumIndex,obj_num__PriceIndex3,obj_num__PriceIndex5,obj_num__NormalisedPopulation,...,obj_to_dum__PropertyAge_7,obj_to_dum__PropertyAge_1,obj_to_dum__PropertyAge_8,obj_to_dum__PropertyAge_9,cyclic__ListDate_week_sin,cyclic__ListDate_week_cos,cyclic__ListDate_month_sin,cyclic__ListDate_month_cos,cyclic__ListDate_month_day_sin,cyclic__ListDate_month_day_cos
0,8270.0,14674.0,13143.0,14224.0,9217.0,10387.0,623.0,13108.0,9022.0,42077.0,...,0,0,0,0,0.781831,0.62349,-1.0,-0.0,0.988468,0.151428
1,3890.0,4172.0,3461.0,4404.0,2958.0,3400.0,1689.0,3695.0,2742.0,77258.0,...,1,0,0,0,0.974928,-0.222521,0.5,0.866025,0.988468,0.151428
2,5900.0,8210.0,6922.0,8952.0,4568.0,4862.0,2351.0,7730.0,3768.0,94514.0,...,0,0,0,0,0.974928,-0.222521,0.0,-1.0,-0.998717,-0.050649
3,7460.0,7309.0,6300.0,7460.0,5361.0,6305.0,1933.0,6290.0,5370.0,82302.0,...,1,0,0,0,0.433884,-0.900969,1.0,0.0,-0.651372,-0.758758
4,6400.0,9182.0,8330.0,9846.0,5428.0,5718.0,482.0,8583.0,4803.0,49176.0,...,0,0,0,0,0.974928,-0.222521,1.0,0.0,0.571268,0.820763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62030,8745.0,15110.0,13468.0,15279.0,9584.0,11626.0,1893.0,13858.0,10012.0,87562.0,...,0,0,0,0,0.974928,-0.222521,1.0,0.0,-0.0,1.0
62031,5360.0,9456.0,8543.0,9420.0,5187.0,6683.0,594.0,8600.0,5439.0,80201.0,...,0,0,0,0,0.974928,-0.222521,-0.866025,0.5,-0.790776,-0.612106
62032,6670.0,8730.0,7217.0,8730.0,6219.0,7620.0,1313.0,7217.0,6219.0,65983.0,...,0,0,0,0,0.781831,0.62349,0.5,-0.866025,-0.651372,-0.758758
62033,6600.0,8546.0,7316.0,8546.0,6311.0,7450.0,837.0,7316.0,6311.0,59780.0,...,0,0,0,0,0.433884,-0.900969,0.866025,-0.5,-0.201299,0.97953
62034,8700.0,12658.0,12002.0,13558.0,8698.0,9514.0,762.0,12824.0,8930.0,38703.0,...,0,1,0,0,0.974928,-0.222521,-0.5,0.866025,0.571268,0.820763

In [28]:
target='Junk'

In [29]:
y_train=all_data[target][all_data['data']=='train']

### Logistic Regression

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV

In [31]:
params={'penalty':['l2'],'class_weight':['balanced',None],
        'C':np.linspace(0.01,100,100)}

In [32]:
model=LogisticRegression()

In [33]:
rs=RandomizedSearchCV(model,param_distributions=params,n_iter=10,
                      scoring='roc_auc',cv=10,n_jobs=-1,verbose=20)

### Splitting the data for train test and validation

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
x_train0 = pd.concat([x_train,y_train], axis = 1)

In [36]:
a_train, a_test = train_test_split(x_train0, test_size = 0.2, random_state=2)

In [37]:
x_train1=a_train.drop(['Junk'],axis=1)
y_train1=a_train['Junk']

In [38]:
x_train_test=a_test.drop(['Junk'],axis=1)

### Fitting the model on train data

In [39]:
rs.fit(x_train1,y_train1)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

RandomizedSearchCV(cv=10, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': array([1.000e-02, 1.020e+00, 2.030e+00, 3.040e+00, 4.050e+00, 5.060e+00,
       6.070e+00, 7.080e+00, 8.090e+00, 9.100e+00, 1.011e+01, 1.112e+01,
       1.213e+01, 1.314e+01, 1.415e+01, 1.516e+01, 1.617e+01, 1.718e+01,
       1.819e+01, 1.920e+01, 2.021e+01, 2.122e+01, 2.223e+01, 2.324e+01,
       2.425e+01, 2....
       7.273e+01, 7.374e+01, 7.475e+01, 7.576e+01, 7.677e+01, 7.778e+01,
       7.879e+01, 7.980e+01, 8.081e+01, 8.182e+01, 8.283e+01, 8.384e+01,
       8.485e+01, 8.586e+01, 8.687e+01, 8.788e+01, 8.889e+01, 8.990e+01,
       9.091e+01, 9.192e+01, 9.293e+01, 9.394e+01, 9.495e+01, 9.596e+01,
       9.697e+01, 9.798e+01, 9.899e+01, 1.000e+02]),
                                        'class_weight': ['balanced', None],
                                        'penalty': ['l2']},
                   scoring='roc_auc', verbose=20)

In [40]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.5f} (std: {1:.5f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [41]:
report(rs.cv_results_,5)

Model with rank: 1
Mean validation score: 0.62645 (std: 0.00933)
Parameters: {'penalty': 'l2', 'class_weight': 'balanced', 'C': 42.43}

Model with rank: 2
Mean validation score: 0.62629 (std: 0.00920)
Parameters: {'penalty': 'l2', 'class_weight': 'balanced', 'C': 27.28}

Model with rank: 3
Mean validation score: 0.62627 (std: 0.00900)
Parameters: {'penalty': 'l2', 'class_weight': 'balanced', 'C': 96.97000000000001}

Model with rank: 4
Mean validation score: 0.60508 (std: 0.01082)
Parameters: {'penalty': 'l2', 'class_weight': None, 'C': 12.13}

Model with rank: 5
Mean validation score: 0.60500 (std: 0.01061)
Parameters: {'penalty': 'l2', 'class_weight': None, 'C': 91.92}

In [42]:
lgrs=rs.best_estimator_

In [43]:
lgrs.fit(x_train1,y_train1)

LogisticRegression(C=42.43, class_weight='balanced')

In [44]:
lgrs.predict_proba(x_train_test)

array([[0.65182872, 0.34817128],
       [0.45555149, 0.54444851],
       [0.64969773, 0.35030227],
       ...,
       [0.52181695, 0.47818305],
       [0.48731131, 0.51268869],
       [0.62907566, 0.37092434]])

### Finding out the probablity on test data

In [45]:
lgrs.predict_proba(x_train_test)[:,1]

array([0.34817128, 0.54444851, 0.35030227, ..., 0.47818305, 0.51268869,
       0.37092434])

In [46]:
testprob=lgrs.predict_proba(x_train_test)[:,1]

In [47]:
y_train_test=a_test['Junk']

In [48]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

In [49]:
lr_auc = roc_auc_score(y_train_test, testprob)

### ROC AUC score

In [50]:
lr_auc

0.6429805114046611

### Now fitting on whole training data set

In [53]:
lgrs.fit(x_train,y_train)

LogisticRegression(C=42.43, class_weight='balanced')

In [54]:
lgrs.predict_proba(x_test)

array([[0.51679943, 0.48320057],
       [0.49785582, 0.50214418],
       [0.63005156, 0.36994844],
       ...,
       [0.74443542, 0.25556458],
       [0.47364867, 0.52635133],
       [0.39831635, 0.60168365]])

In [55]:
lgrs.predict_proba(x_test)[:,1]

array([0.48320057, 0.50214418, 0.36994844, ..., 0.25556458, 0.52635133,
       0.60168365])

In [56]:
predprob=lgrs.predict_proba(x_train_test)[:,1]

In [57]:
submissions=pd.DataFrame({'Junk':lgrs.predict_proba(x_test)[:,1]})

### Final Submission 01

In [58]:
submissions.to_csv('sample_submission_01.csv',index=False)